### ISSUE TITLE
"Add/Remove Columns" blanks

### ISSUE THREAD

**Issue by rperlin-ela** [Language-Mapping/language-map#137] opened 2020-11-21 18:17 UTC
## Summary

Not really a bug, but a little strange when you click "Add/Remove Columns" in Data and the top two are blank. I understand why, but would it be ok if we title them "View in Map" and "Description" respectively?

**Comment by abettermap** [comment] 2020-11-21 20:50
i spent some time on this one awhile back and i believe those are all tied very directly to the column titles, and i don't think there's a way to battle the Material Table plugin. if you are okay with having those as column titles in the table, that seems doable, but those first two fixed columns will take up a lot of space on mobile. i guess i've just been focused on making those titles hidden so that we could keep the first two columns fixed on mobile since annoying to have to scroll all the way back left to get to the interactive buttons. 

i put a LOT of work into the fixed columns so let's keep that. not sure how i'd fix the column selection blanks, which i very much regret ever including since i never use it and it's caused nothing but UI problems and now more UI problems. the gift that keeps on giving, ha!

**Comment by abettermap** [comment] 2020-11-21 22:19
actually i was able to do it hackily by setting the font size to 0 for the first two headers, and using the desired titles:

![image](https://user-images.githubusercontent.com/4974087/99888820-b7cfa300-2c0c-11eb-8483-50ec613cf246.png)

it might be a little confusing that way since it's hidden in the heading but not the column toggle menu, but it's better than the blanks in the column toggle menu!

**Comment by rperlin-ela** [comment] 2020-11-22 01:07
Thank you!!

**Closed** 2020-11-30 03:27 UTC
Labels: effort: 3:3rd_place_medal: (high):3rd_place_medal:

**Comment by abettermap** [comment] 2020-12-07 16:39
oops, already had an issue for this. dupe of #91
